# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 16:03
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171011_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='===', editable=False, populate_from='username'),
            preserve_default=False,
        ),
    ]
