# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_answer'),
        ('question', '0002_auto_20171030_1216'),
    ]

    operations = [
    ]
